* words

** neck <2016-06-21 Tue>
 英  [nek]   美  [nɛk]
n. 脖子；衣领；海峡
vi. 搂著脖子亲吻；变狭窄
vt. 使变细；与…搂著脖子亲吻
n. (Neck)人名；(德、意、英)内克
 柯林斯英汉双解大词典  21世纪大英汉词典

neck /nɛk/  CET4 TEM4
N-COUNT Your neck is the part of your body which joins your head to the rest of your body. 颈
例：
She threw her arms around his neck and hugged him warmly.
她伸出双臂搂住他的脖子，热烈地拥抱他。
N-COUNT The neck of an article of clothing such as a shirt, dress, or sweater is the part which surrounds your neck. 领口
例：
...the low, ruffled neck of her blouse.
…她褶边低胸的衬衫领口。
N-COUNT The neck of something such as a bottle or a guitar is the long narrow part at one end of it. (瓶子、吉他等的) 颈状部位
例：
Catherine gripped the broken neck of the bottle.
凯瑟琳紧握着破裂的瓶颈。
PHRASE If you say that someone is breathing down your neck, you mean that they are watching you very closely and checking everything you do. 密切监视
例：
Most farmers have loan officers breathing down their necks.
大多数农场主受到信贷员的密切监视。
PHRASE In a competition, especially an election, if two or more competitors are neck and neck, they are level with each other and have an equal chance of winning. 势均力敌
例：
The latest polls indicate that the two main parties are neck and neck.
最新的民意测验显示两个主要政党势均力敌。
PHRASE If you stick your neck out, you bravely say or do something that might be criticized or might turn out to be wrong. 敢说敢干
例：
During my political life I've earned myself a reputation as someone who'll stick his neck out, a bit of a rebel.
我在自己的政治生涯中得了一个敢说敢干、有点叛逆的名声。
网络释义 专业释义 英英释义

 脖子
 颈
 颈部
 颈
短语
Stiff neck 落枕
Stiff neck 脖子发僵
Stiff neck 落枕
Stiff neck 顽固之人
goose neck 鹅颈管
  更多结果
词组短语 同近义词 同根词

neck and neck 并驾齐驱，不分上下
bottle neck 瓶颈
pain in the neck 极讨厌的人或事
stiff neck 脖子发僵，斜颈；顽固之人
neck of the woods 附近一带（一般指乡村地区）
  更多词组短语
双语例句 原声例句 权威例句

He draped his arms round her neck.
他双手搂住了她的脖子。 
The rain was dripping down his neck.
雨水沿着他的脖子往下滴。 
The doll pivots at the waist and neck.
那洋娃娃的腰和颈可以转动。 
 更多双语例句
百科

Neck

The neck is the part of the body, on many terrestrial or secondarily aquatic vertebrates, that distinguishes the head from the torso or trunk. The adjective (from Latin) signifying "of the neck" is cervical (though in non-technical contexts, this is more frequently used to describe the cervix).
来源于：维基百科

literate 
 英  ['lɪt(ə)rət]   美  ['lɪtərət]
adj. 受过教育的；精通文学的
n. 学者
 柯林斯英汉双解大词典  21世纪大英汉词典

literate /ˈlɪtərɪt/  CET6+ TEM8
ADJ Someone who is literate is able to read and write. 能读会写的
例：
Over one-quarter of the adult population are not fully literate.
四分之一以上的成年人是半文盲。
→ see also computer-literate
网络释义 专业释义 英英释义

 有文化的
 有读写能力的
 识字的
 学者
短语
Literate programming 文学编程
Literate programming 文学编程
Literate programming 文学化编程
Literate programming 字面编程
Financially Literate 掌握一定财务知识
  更多结果
词组短语 同近义词 同根词

computer literate 懂电脑
双语例句 原声例句 权威例句

The drawback of the internet is that you have to be literate to use it.
互联网的缺点就是人们必须得有文化才能使用它。 
article.yeeyan.org
 更多双语例句
百科

Literate

Literacy is traditionally understood as the ability to read and write. The term's meaning has been expanded to include the ability to use language, numbers, images and other means to understand and use the dominant symbol systems of a culture. The concept of literacy is expanding in OECD countries to include skills to access knowledge through technology and ability to assess complex contexts.Literacy represents the lifelong, intellectual process of gaining meaning from a critical interpretation of written or printed text. The key to all literacy is reading development, a progression of skills that begins with the ability to understand spoken words and decode written words, and culminates in the deep understanding of text. Reading development involves a range of complex language underpinnings including awareness of speech sounds (phonology), spelling patterns (orthography), word meaning (semantics), grammar (syntax) and patterns of word formation (morphology), all of which provide a necessary platform for reading fluency and comprehension. Once these skills are acquired, the reader can attain full language literacy, which includes the abilities to apply to printed material critical analysis, inference and synthesis; to write with accuracy and coherence; and to use information and insights from text as the basis for informed decisions and creative thought. The inability to do so is called illiteracy or analphabetism.The United Nations Educational, Scientific and Cultural Organization (UNESCO) defines literacy as the "ability to identify, understand, interpret, create, communicate and compute, using printed and written materials associated with varying contexts. Literacy involves a continuum of learning in enabling individuals to achieve their goals, to develop their knowledge and potential, and to participate fully in their community and wider society".
来源于：维基百科

* Lesson<2016-06-21 Tue>
** Lesson thirteen
Why does the giraffe like to eat leaves from tall trees? It like to do
so because it has a long neck.

Why are the girls sleeping during the lesson? They are sleeping
because the lesson is boring.

Why are these girls not working and instead spending time at the
beach? They are spending time at the beach because they are on
holiday.

Why are the swans not talking on the telehpone? They are not talking
on the telephone because they do not have a telephone.

Why are there many tourists taking photos of the square? They are
taking photos of it because it is beautiful.

Why are people sleeping on the grass? They are sleeping here because
they do not have a home.
** Lesson Sixteen
*** words

menu 
 英  ['menjuː]   美  ['mɛnju]
n. 菜单
饭菜
 柯林斯英汉双解大词典  21世纪大英汉词典

menu /ˈmɛnjuː/  CET4 TEM4
N-COUNT In a restaurant or café or at a formal meal, the menu is a list of the meals and drinks that are available. 菜单
例：
A waiter offered him the menu.
一个侍者给他送上了菜单。
N-COUNT A menu is the food that you serve at a meal. 饭菜
例：
Try out the menu on a few friends.
请几个朋友来尝尝这道菜。
N-COUNT On a computer screen, a menu is a list of choices. Each choice represents something that you can do using the computer. (电脑屏幕上的) 菜单
例：
Hold down the shift key and press F7 to display the print menu.
按住键的同时按下键，以显示打印菜单。
网络释义 专业释义 英英释义

 菜单
 菜单
 选单
 菜单键
短语
Menu Bar 菜单栏
Menu Bar 菜单条
Menu Bar 功能表列
Menu Bar 主菜单
context Menu 上下文菜单
  更多结果
词组短语 同近义词

menu item [计]菜单项
menu bar n. [计]菜单栏
main menu 主菜单；主选单；炙单
shortcut menu [计]快捷菜单
drop-down menu 下拉式菜单
  更多词组短语
双语例句 原声例句 权威例句

Let us see what is on the menu today.
让我们看看今天的菜单上有些什么菜。 
It provides an event handler for each menu option.
它为每一个菜单选项提供事件处理程序。 
www.ibm.com
Since her eyes now see only large shapes and shadows, I had to read the menu for both of us.
由于她现在的视力只能看到大致的形状和模糊的影子, 我得为我俩读菜单。 
www.ebigear.com
 更多双语例句
百科

Menu

In a restaurant, a menu is a presentation of food and beverage offerings. A menu may be à la carte – which guests use to choose from a list of options – or table d'hôte, in which case a pre-established sequence of courses is served.
来源于：维基百科

a menu
a napkin

A napkin is a square of cloth or paper that you use when you eating to
protect your clothes, or to wipe your mouth or hands.
a tablecloth
a tray

A tray is a flat piece of wood, plastic, or metel, which usually has
raised edges and which is used for carrying things, especially food
and drinks.

a bill

A bill is a written statement of money that you owe for goods or
serices.

a waiter

A waiter is a man who works in a restaurant, serving people food and
drink.

to take away

If you take away from someone, you remove it from them, so that they
no longer possess it or have it with them.

to taste

Taste is one of the five senses that people have. When you have food
or krink in your mouth, youir sense of taste makes it possible for you
to recognize what it is.

to pour
to like
to bring
to order

a spoon
a knife
a fork
a cup
a wineglass
*** text
They are sitting ta the table in a restaturant.
The wife orders chicken with potatoes.
They read the munu.
The husband and wife go to a restaurant.
The husband orders meat.
The waiter brings the menu.

There is water in the bottle.
The waiter brings a  tray.
The waiter pours out some wine.
There is wine in the bottle.
He is pouring some wine into a glass.
There are plates and bottles on the tray.

The fork is on the left of the plate.
There are napkins near the plates.
The knife and spoon are on the right of the plate.
A clean white tablecloth is on the table.
There are plates on the tablecloth.
There is a wineglass behind the plate.

He likes meat.
The wife is pouring water into the glass, she does not want wine.
He says to his wife, " I like meat very much".
The husband is tasting the meat.
The husband is drinking wine, he does not want water.
The husband and wife are hungry.

The wife tasting the chicken.
The waiter brings cups of coffee.
The waiter takes the chicken away.
She looks at the menu.
She does not like the chicken. The chicken is cold.
The wife puts sugar into hot coffee.

The husband looks at the bill.
The waiter brings the bill.
He pays the waiter.
The wife drinks coffee with sugar.
The waiter takes the dirty dishes away.
The husband drinks coffe without sugar.

The girl likes icecream.
The man likes spaghetti.
It likes to dance.
They like to swim.
The girl like to sing.
The man likes the woman.
** Lesson seventeen<2016-06-22 Wed 06:19>
a customer
sale
price
a shop assistant
discount
a counter

old
new
to pay cash
to pay by card
expensive
cheap

gloves
a robe
goods
a jacket
a hat
clothes

There are lots of goods in the big shop.
There are lots of customers in the shop.
The shop assistant is selling goods.
The shop assistant is standing behind the counter.
The shop sells clothes.
There is a sale in the shop.

The customers enjoy the sale.
The clothes are cheap.
There are high prices in the shop. Customers don't like high prices.
The car is expensive.
They like to buy goods at a discount.
The shop has a lot of goods at a discount.

The shop sells hats.
The man has an old hat.
The girl wants to buy cheap clothes.
The shop doesn't have any old dresses. All the dresses are new.
There aren't any people in the expensive shop.
The woman wants to buy a new dress.

The woman likes to shop.
The man does not like to shop.
The little girl wants to buy some gloves.
The boy pays cash
The girl is paying by card.
The shop assistant is giving her gloves.

The shop sells a lot of scarves.
He likes the black suit.
The man wants to buy a suit.
She likes the white rob.
The little girl wants to buy a scarf.
The woman wants to buy a robe.

Is the car expensive? Yes, it's expensive.
Is the fruit cheap? Yes, it's cheap.
Is the dress new? Yes, it is new.
Is the girl paying by card? Yes, she is paying by card.
Is the man paying cash? Yes, he is paying cash.
Are the shoes old? Yes, they are old.

Does the shop sell goods at a discount or without a discount? It sells
goods at a discount.
Is the customer paying cash or by card? He is paying cash.
Who is behind the counter? The shop assistant is behind the counter.
Is the woman buying a dress or some gloves? She is buying a dress.
Does the shop sell clothes or food? They sell clothes here.
Is the man buying a suit or a hat? He is buying a hat.

*** words

** neck <2016-06-21 Tue>
 英  [nek]   美  [nɛk]
n. 脖子；衣领；海峡
vi. 搂著脖子亲吻；变狭窄
vt. 使变细；与…搂著脖子亲吻
n. (Neck)人名；(德、意、英)内克
 柯林斯英汉双解大词典  21世纪大英汉词典

neck /nɛk/  CET4 TEM4
N-COUNT Your neck is the part of your body which joins your head to the rest of your body. 颈
例：
She threw her arms around his neck and hugged him warmly.
她伸出双臂搂住他的脖子，热烈地拥抱他。
N-COUNT The neck of an article of clothing such as a shirt, dress, or sweater is the part which surrounds your neck. 领口
例：
...the low, ruffled neck of her blouse.
…她褶边低胸的衬衫领口。
N-COUNT The neck of something such as a bottle or a guitar is the long narrow part at one end of it. (瓶子、吉他等的) 颈状部位
例：
Catherine gripped the broken neck of the bottle.
凯瑟琳紧握着破裂的瓶颈。
PHRASE If you say that someone is breathing down your neck, you mean that they are watching you very closely and checking everything you do. 密切监视
例：
Most farmers have loan officers breathing down their necks.
大多数农场主受到信贷员的密切监视。
PHRASE In a competition, especially an election, if two or more competitors are neck and neck, they are level with each other and have an equal chance of winning. 势均力敌
例：
The latest polls indicate that the two main parties are neck and neck.
最新的民意测验显示两个主要政党势均力敌。
PHRASE If you stick your neck out, you bravely say or do something that might be criticized or might turn out to be wrong. 敢说敢干
例：
During my political life I've earned myself a reputation as someone who'll stick his neck out, a bit of a rebel.
我在自己的政治生涯中得了一个敢说敢干、有点叛逆的名声。
网络释义 专业释义 英英释义

 脖子
 颈
 颈部
 颈
短语
Stiff neck 落枕
Stiff neck 脖子发僵
Stiff neck 落枕
Stiff neck 顽固之人
goose neck 鹅颈管
  更多结果
词组短语 同近义词 同根词

neck and neck 并驾齐驱，不分上下
bottle neck 瓶颈
pain in the neck 极讨厌的人或事
stiff neck 脖子发僵，斜颈；顽固之人
neck of the woods 附近一带（一般指乡村地区）
  更多词组短语
双语例句 原声例句 权威例句

He draped his arms round her neck.
他双手搂住了她的脖子。 
The rain was dripping down his neck.
雨水沿着他的脖子往下滴。 
The doll pivots at the waist and neck.
那洋娃娃的腰和颈可以转动。 
 更多双语例句
百科

Neck

The neck is the part of the body, on many terrestrial or secondarily aquatic vertebrates, that distinguishes the head from the torso or trunk. The adjective (from Latin) signifying "of the neck" is cervical (though in non-technical contexts, this is more frequently used to describe the cervix).
来源于：维基百科

** Lesson<2016-06-21 Tue>
** Lesson thirteen
This elderly man is wearing glasses. he is hugging a large white dog
around the  neck and laughing.
This is a view of the desert. A group of people are travelling on
camels. Three camels are lying in the sand, and two are standing.
These young people are also travelling across the desert. They like to
travel on fourwheelers.
This is a small, beautiful money. It is eating for lunch. In front of
it are two plates of food.
It is a summer's day in the countryside. There is a horse standing
under the tree. It is relaxing.
It is a sunny day. The sportsmen are relaxing at a table in the
café. One of them is drinking water from a bottle.
The elderly man is sitting on a stool under the tree. His white cap is
lying on the grass.
A knife and a fork are lying on a napkin, the napkin is lying on a
white tablecloth, and the tablecloth is lying on a table.
This is a restaurant. The young man is paying the waiter in
cash. There is a cup of coffee in front of him.
The girl with glasses is drawing. There is a fish and beautiful sea
plants in the picture. Two girl are looking at her work.
The young man is taking a phone of the girl with long black
hair. There is a small white dog sitting on the girl's lap.
lap :n. 一圈；膝盖；下摆；山坳
vt. 使重叠；拍打；包围
vi. 重叠；轻拍；围住
Two girls are sitting on a bench in the park. They are wearing white
pants. One of them is holding an umbrella.
The customer who is standing in front of the mirror wants to buy a
skirt.
The turtle is an animal that moves very slowly.
The woman who is sitting to the left of the boy is a teacher.
The cactus is a plant that is able to live in the desert.
A seagull is a bird that lives at the sea.
Rome is a city that tourists like very much.
When there is good weather outside the window in the house is open.
When a person is ill， he goes to the doctor.
Many customers come to the big shop when there is a sale.
When there is a trffice jam, the policemen have a lot of work.
When it is raining, people open their umbrellas.
When the parents work， the child plays with his grandmother.

The man is turning off the television, because he does not want to
watch it any longer.
The tourists are travelling on the ship, becasue they do not like to
fly on airplanes.
The waiter is taking away the chicken, because the woman does not like
it.
The woman is drinking water, because she does not want to drink wine.
The man is drink wine, because he likes it.
The boy is turning off the computer, because he does not want to play
any longer.

The spectators are going to the theatre in order to watch the
performance.
The woman is not drinking wine in order to drive the car well.
The man is turning on the television in order to watch an interesting
programme.
The actors are going to the theatre in order to perform on stage.
The boy is turning on the computer in order to play.
The customers are going to the shop at the time of sale in order to
buy cheap goods.

The woman does not like the chicken, although it tastes good.
The boy is turning on the computer, although his parents would rather
him not.
The woman wants to buy a new dress, even though she has many dresses.
The girl likes to walk in the forest, though it is raining.
The woman is drinking water, although she likes wine.
The girl is not happy, even though today is her birthday.

Today is the little boy's birthday. He is holding a present in his
hands. He likes this holiday very much.
There is a beautiful, tan saleswoman behind the counter in the small
shop. There is only one customer in the shop, and he is looking at
wine and fruits.
The weather is rainy. The boy is looking out of the window. He is
bored, and wants to walk and play outside.
This is a bus stop. A man is sitting on the bench and reading the
newpaper. He is waiting for the bus.
The woman is standing by the sea. She is neither bathing nor
tanning. She is looking at the sea and waiting for a ship.
Two women in the park are looking at the big grey bird. One woman is
holding an orange. She wants to feed the bird.

Two cheerful girls are walking in the autumn park. They like to play
with the beautiful yellow leaves.
This is a young woman in blue. She has long hair and beautiful
blue eyes. She is holding a white cup.
This is a large brown bear. It is getting out of the water, and the
lake and the mountains are behind him.
The bride and groom are celebrating their wedding on the beach at the
sea. The groom is holding the bride in his arms. She is wearing a long
white dress and has flowers in her hand.
This is a large, beautiful, red and white house. Next to the house is
a table and four chairs. There are small trees growing across from the
house.
The man wants to give flowers to the woman in the beautiful dress. He
is holding them behind his back, and she is looking at him and
laughing.

Why does the giraffe like to eat leaves from tall tree? It likes to do
so because it has a long neck.
Why are there many tourists taking photos of the square? They are
taking photos of it because it is beautiful.
Why are the girls sleeping during the lesson? They are sleeping
because the lesson is boring.
Why are people  sleeping on the grass? They are sleeping here
because they do not have a home.
Why are the swans not talking on the telephone? They are not talking
on the telephone because they do not have a telephone.
Why are these girls not working and instead spending time at the
beach? They are spending time at the beach because they are on
holiday.
** lesson eighteen
to have
to have not
to put on
to take off
to try on
to wear
The girl has a toys.
The woman does‘nt ant toys.
The boy doesn't have a bicycle.
The boy has a bicycle.
The girl has a boys.
The man doesn't have a bicycle.
The girl has a flower.
The boy doesn't have a flower.
The girl has parents.
The girl has a grandma and grandad.
The girl has a yellow dress.
The girl has a brother.
The girl has an apple.
The girl has a big dog.

The boy doesn't have a helicopter or a giraffe.
The giraffe hasn't got any money.
The boy doesn't have long hair.
The boy doesn't have a sister.
The boy doesn't have a dress.
The boy doesn't have a dog.

The litter girl wants to try on a skirt.
The man is trying on some shoes.
The man is trying on a shirt.
The woman is trying on a shirt
The girl is trying on a skirt in front of the mirror.
The girl is trying on some shoes.
sweater
 英  ['swetə]   美  ['swɛtɚ]
n. 毛线衣，运动衫；大量出汗的人，发汗剂

The girl is taking off a green sweater.
The girl is taking off a balck-and-white dress.
The man is putting on some gloves.
The woman is putting on some gloves.
The woman is putting on boots.
The man is taking off a shirt.

The boy isn't wearing a dress.
moustache
 英  [mə'stɑːʃ]   美  [mə'stɑʃ]
n. 小胡子；髭；触须
n. (Moustache)人名；(法)穆斯塔什
Grandad has a moustache and a beard
beard
 英  [bɪəd]   美  [bɪrd]
vt. 公然反对；抓…的胡须
n. 胡须；颌毛
vi. 充当掩护；充当男随员
n. (Beard)人名；(英)比尔德
The girl wears a dress.
The giraffe does not wear clothes.
Grandma wears glasses.
The woman wears shoes.

The man doesn't have any money. He can't buy anything.
The family has a big new house.
The woman is putting on a  white dress for the wedding.
Girls like to wear short skirts.
The man has a lot of money. He can buy a car.
The girl has a new pink bag.

Do women wear skirts? Yes, they wear skirts.
Do men wear skirts? Yes, they wear skirts sometimes.
Does grandma wear glasses? Yes,  grandma wears glasses.
Do they wear gloves in winter? Yes, they wear gloves in winter.
Do they wear swimsuits in summer? Yes, they wear swimsuits in summer.
Has the boy got a bicycle? Yes, he has  a bicycle.

What is the girl taking off? She is taking off a black-and-white dress.
Has the dog got any money? No, it has not got any money.
Has the dog got any clothes? No, it has not got any clothes.
Who is trying on the skirt? The girl in front of the mirror is trying on the skirt.
Who has a beard? Grandad has a beard.
Is the woman putting on shoes or gloves? She is putting on gloves.
95.4%
** lesson nineteen<2016-07-07 Thu> 
:LOGBOOK:
CLOCK: [2016-07-07 Thu 04:17]--[2016-07-07 Thu 04:42] =>  0:25
:END:
a cheek
an ear 
an eye 
a face
a nose
a mouth

a stomach
shoulders
a neck 
a body
a head
a back

an arm 
a foot 
a leg
a hand
a finger
kness
 
a child's face
a woman's face
The woman has a long neck.
The giraffe has a very long neck.
A man's face
The man is on his knees.
knees 
 英  [niːz]   美  [niːz]
[解剖] 膝

big stomach
The boy has dirty cheeks.
The boy has a big nose.
Mother kisses her son's pink cheek.
The girl is wearing a scarf on her neck and a cap  on her head.
The man has a wide back.

a woman's ear 
a finger on the computer
an open mouth
closed eyes
a closed mouth
open eyes

The woman is putting a glove on her hand.
a woman with her eyes closed.
The girl has shoes on her feet.
The girl does not have any shoes on her feet.
The son is sitting on his father's shoulders.
The child is sitting on his mother's knee.

The child's foot is in his mother's hands.
The man is holding a finger in his mouth.
The child is in his mother's arms.
The child's hand is holding his mother's finger.
a grown-up's leg
a grown-up's foot

Is the white-haired girl speaking in the black-haired girl's ear? Yes, she is speaking on the balck-haired ear.
Is this face sad? Yes, it is sad.
Is the boy speaking in his friend's ear? Yes, he is speaking in his friend's
ear.
Is this face cheerful? Yes, it is cheerful.
Does the bear have a short neck? Yes, it does have a short neck.
Is the woman putting a hat on her head? Yes, she is putting a hat on her head.

Is the child's head big or small? His head is small.
Is this a woman's face or a man's face? This is a man's face.
Is  mother kissing her son's cheek or nose? She is kissing her son's cheek.
Is the child sitting on his mother's or grandma's knee? He is sitting on his
grandma's knee.
Is the child's face clean or dirty? His face is clean.
Are the child's feet big or small? His feet are small.
96.9% 
** DONE lesson twenty
CLOSED: [2016-07-07 Thu 20:39]
a policeman
a teacher
a cooker
a builder
a docter

to teach
to cook 
to drive
to jump
to treat 

a hospital
a patient
a school
a schoolboy
a stadium
a lesson

The builders are building a house.
The cook is cooking food.
The dirver is driving a car.
The policeman is running with a dog.
The doctor is treating a patient.
The teacher is giving a lesson.

The shop assistant works in a shop.
The cook works in a reastaurant.
The policeman works outdoors.
The waiter works also in a reastaurant.
The doctors work in a hospital.
The teacher works in a school.

The waiter's job is to bring food.
The teacher's job is to teach children.
The cook's job is to cook food.
The builder's job is to build houses.
The doctor's job is to treat patients.
The driver's job is to drive a car.

The schoolchildren are listening to the teacher.
The shop assistant is speaking to the customer.
This ia a sportsman. He is running.
The sportsman is jumping at the stadium.
The policeman is riding a horse through the street.
The teachers are sitting at the table.

There are a lot of people in the restaurant.
There are a lot of schoolchildren in the school.
There is a lot of food on the cook's table.
There are a lot of patients in the hospital.
There policeman has a lot of work outdoors.
There are a lot of sportsmen at the stadium.

Where does the teacher work? He works in a school.
Where does the shop assistant work? He works in a shop.
Where does the builder work? He works outdoors.
Where does the policeman work? He works outdoors too.
Where does the waiter work? He works in a restaurant too.
Where does the cooker wrok? He works in a restaurant.

Is eating a job? No, it is not a job.
Is drinking coffee a job? No, it is not a job.
Is treating patients a sportsman's job or a doctor's job? It is a doctor's job.
Is building houses a shop assistant's job or a builder's job? It is a builder's job.
Is sleeping a job? No, it is not a job.
Is teaching children a teacher's job or a waiter's job? It is a teacher's job.
96.5%
** DONE lesson twenty one
CLOSED: [2016-07-08 Fri 06:01]
The policeman is wearing a blue cap.
The doctor is wearing a white gown.
The customer is trying on the shirt.

What colour is the excavator? It is yellow.
What colour is the umbrella? It is red.
What colour is the sky? It is blue.
What colour is the doctor's gown? It is white.
What colour are the woman's shoes? They are black.
What clour is the flower in the girl's hand? It is red.

Who is the driver driving? He is dring the girl.
To whom is the bridegroom giving the flowers? He is giving to the bride.
To whom is the shop assistant selling? He is selling to the customer.
Who is the doctor treating? He is treating the patient.
Who is the customer paying? He is paying the shop assistant.
To whom is the boy giving the banana? He is giving the banana to the cat.

Who is treating the patients? The doctor.
Who is bringing the paltes of food? The waiter.
Who is teaching the children? The teacher.
Who is building the house? The builders.
Who is paying money? The customer is paying money.
Who is jumping at the stadium? The sportsman.

What is the cook cooking? He is cooking food.
What are the builders building? They are building the house.
What is the shop assistant selling? He is selling clothing.
What is the waiter bringing? He is bringing plates of food.
What are the children reading in the lesson? They are reading a book.
What is the driver drinking? He is drinking a car.

Where do they teach children? At school.
Where do they cook the food? In the kitchen.
Where do they watch the sportsmen? At the stadium.
Where do they build the houses? Outside.
Where do they buy shoes? They also buy them at the shop.
Where do they buy food? At the shop.
one two three four five six seven eight nine ten more less 

How many fingers does a person have on one hand? A person has five fingers.
How may eyes does a person have? A person has two eyes.
How many legs does a dog have? A dog has four legs.
How many bicycles does the boy have? He has one bicycle.
How many fingers does a person have? A person has ten fingers.
How many legs does a person have? A person has two legs.

There are four chairs around the table.
A child has fewer legs than a cat.
There are three children in the family.
A dog has more legs than a person.
There are nine apples here.
There are six forks on the table.
97.4% 
** DONE lesson twenty two
CLOSED: [2016-07-08 Fri 17:17]
an artist
a secretary
an actor 
a singer
a photographer
a musician

theatre
stage
performance
a mask
a spectator 
concert

to paly the guitar
ungly
interesting
boring
to play a role
beautiful

the spectators at the stadium
The spacetators in the theatre.
jazz musicians
theatre building
a jolly performance
jazz concert

This is the actres befor the performance.
Theis is a boy in a black mask.
There are no people on this stage.
This is a small stage in a small theatre.
These are the musicians during the concert.
These are venetain masks.

To sing this is the work of a singer.
To play on the stage this is the work of an actor.
To draw this is the work of an artist.
To photograph this is the work of a photographer.
To performa a concert this is the work of musicians.
To speak on the telephone this is one of the jobs of a secretary.

This actress acts in the theatre.
The man and the woman are playing their roles in masks.
The boy with the long black hair is playing the guitar.
The boy in blue is playing the guitar.
This man is playing the role of a woman.
This actor acts in film.

not such a beautiful wife
a beautiful wall
an ugly apple
a beautiful apple
a beautiful wife
an ugly wall

an boring lesson
a boring book
boring work
interesting work
a boring lesson
an interesting book
an interesting lesson

The aritst is painting a beatiful picture.
The spectators are waiting for the performance.
There are two musicians on stage.
The secretary has a lot of boring work.
The singer on stage is singing and playing the guitar.
The photographer has interesting work.
95.9%




