* words

** neck <2016-06-21 Tue>
 英  [nek]   美  [nɛk]
n. 脖子；衣领；海峡
vi. 搂著脖子亲吻；变狭窄
vt. 使变细；与…搂著脖子亲吻
n. (Neck)人名；(德、意、英)内克
 柯林斯英汉双解大词典  21世纪大英汉词典

neck /nɛk/  CET4 TEM4
N-COUNT Your neck is the part of your body which joins your head to the rest of your body. 颈
例：
She threw her arms around his neck and hugged him warmly.
她伸出双臂搂住他的脖子，热烈地拥抱他。
N-COUNT The neck of an article of clothing such as a shirt, dress, or sweater is the part which surrounds your neck. 领口
例：
...the low, ruffled neck of her blouse.
…她褶边低胸的衬衫领口。
N-COUNT The neck of something such as a bottle or a guitar is the long narrow part at one end of it. (瓶子、吉他等的) 颈状部位
例：
Catherine gripped the broken neck of the bottle.
凯瑟琳紧握着破裂的瓶颈。
PHRASE If you say that someone is breathing down your neck, you mean that they are watching you very closely and checking everything you do. 密切监视
例：
Most farmers have loan officers breathing down their necks.
大多数农场主受到信贷员的密切监视。
PHRASE In a competition, especially an election, if two or more competitors are neck and neck, they are level with each other and have an equal chance of winning. 势均力敌
例：
The latest polls indicate that the two main parties are neck and neck.
最新的民意测验显示两个主要政党势均力敌。
PHRASE If you stick your neck out, you bravely say or do something that might be criticized or might turn out to be wrong. 敢说敢干
例：
During my political life I've earned myself a reputation as someone who'll stick his neck out, a bit of a rebel.
我在自己的政治生涯中得了一个敢说敢干、有点叛逆的名声。
网络释义 专业释义 英英释义

 脖子
 颈
 颈部
 颈
短语
Stiff neck 落枕
Stiff neck 脖子发僵
Stiff neck 落枕
Stiff neck 顽固之人
goose neck 鹅颈管
  更多结果
词组短语 同近义词 同根词

neck and neck 并驾齐驱，不分上下
bottle neck 瓶颈
pain in the neck 极讨厌的人或事
stiff neck 脖子发僵，斜颈；顽固之人
neck of the woods 附近一带（一般指乡村地区）
  更多词组短语
双语例句 原声例句 权威例句

He draped his arms round her neck.
他双手搂住了她的脖子。 
The rain was dripping down his neck.
雨水沿着他的脖子往下滴。 
The doll pivots at the waist and neck.
那洋娃娃的腰和颈可以转动。 
 更多双语例句
百科

Neck

The neck is the part of the body, on many terrestrial or secondarily aquatic vertebrates, that distinguishes the head from the torso or trunk. The adjective (from Latin) signifying "of the neck" is cervical (though in non-technical contexts, this is more frequently used to describe the cervix).
来源于：维基百科

* Lesson<2016-06-21 Tue>
** Lesson thirteen
Why does the giraffe like to eat leaves from tall trees? It like to do
so because it has a long neck.

Why are the girls sleeping during the lesson? They are sleeping
because the lesson is boring.

Why are these girls not working and instead spending time at the
beach? They are spending time at the beach because they are on
holiday.

Why are the swans not talking on the telehpone? They are not talking
on the telephone because they do not have a telephone.

Why are there many tourists taking photos of the square? They are
taking photos of it because it is beautiful.

Why are people sleeping on the grass? They are sleeping here because
they do not have a home.
